# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lZGTjTOE_IBiisoq4HjOZE8jMBmNwNiW
"""

a=int(input())
b=int(input())
c=int(input())
if round((((a**2+b**3)/(c+3))/4))%2==0:
  print('true')
else:
  print('false')

a=int(input())
if a==1:
  print('january')
elif a==2:
  print('february')
elif a==3:
  print('march')
elif a==4:
  print('april')
elif a==5:
  print('may')
elif a==6:
  print('june')
elif a==7:
  print('jule')
elif a==8:
  print('august')
elif a==9:
  print('september')
elif a==10:
  print('october')
elif a==11:
  print('november')
else:
  print('december')

a=int(input())
if a>40:
  print('stonks')
else:
  print('not stonks')

a=int(input())
if a//2==0:
  print('chet')
else:
  print('nechet')

def  is_year_leap(y):
  if (y%100!=0 or y%400!=0) and (y%4==0):
    return True
  else:
    return False
y=int(input())
print(is_year_leap(y))

def is_prime(n):
  for i in range(2, (n//2)+1):
    if n%i==0:
      return False
  return True
n=int(input())
print(is_prime(n))

a=float(input())
b=float(input())
l=(-138/2)**1.3
p=abs((-69/28**5.1)*4)
if a/b==3.6:
  c=a
  a=b
  b=c
elif b>l and b<p:
  c=a
  a=b
  b=c
print(a,b)

a=input()
b=input()
c=input()
d=input()
e=input()